#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string | nil
    required: false
  storeNumber:
    type: integer | nil
    required: false
  deliveryStreamNumber:
    type: integer | nil
    required: false
  deliveryStreamName:
    type: string | nil
    required: false
  schemaName:
    type: string | nil
    required: false
  deliverySchemaType:
    type: integer | nil
    required: false
  startDate:
    type: date-only | nil
    required: false
  endDate:
    type: date-only | nil
    required: false
  createdBy:
    type: string | nil
    required: false
  creationDateTime:
    type: string | nil
    required: false
  updatedBy:
    type: string | nil
    required: false
  updateDateTime:
    type: string | nil
    required: false



        



