#%RAML 1.0 Library
usage: This Library should be included in all projects unless there is a good reason not to

resourceTypes:
  healthCheck: !include /exchange_module/ah-svc-mvp/health-check/1.0.0/health-check.raml