#%RAML 1.0 ResourceType

usage: Use this Resource to add a health check to your API, you should always /healthcheck path in the root of your API
description: performs and healthcheck and return status
get:
  responses:
    200:
      description: API is healthy and working normally
    500:
      description: There is an issue with the API and the downstream system
      body:
        application/json:
          type: object
          properties:
            error-code:
              type: string
              required: true
            message:
              type: string
              required: true