name: deliveryscapi
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: 59ae6b648ca3437aae3a.westeurope.aksapp.io
framework: java8

database:
  required: false


ingress:
  required: true
  site: deliveryscapi
  path: /

image:
  name: deliveryscapi
  version: latest